# Server Port
server.port=8080

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:newsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# A strong, random, base64-encoded secret key
# You can generate one online (e.g., "base64 encode random 32 byte string")
jwt.secret.key=ee4414a59a225bae8ac68b82cb24b412a96b26bfef76982b45c810985ef18939

# API Key for the external news service
# Get yours from https://newsapi.org/
newsapi.key=9a87d1d2dd574ca381f337d0fb11618a